### ISSUE TITLE
haikro doesn't work with zshell

### ISSUE THREAD

**Issue by JakeChampion** [matthew-andrews/haikro#100]
It seems the file expansion in the tar command works differently on bash compared to zshell. This makes the tarred folder made via zshell much larger than the one with bash. Another difference is zshell's tarred folder contains a folder named `app` which then contains the application files whereas bash's tarred folder only contains the application files at the root of the tar file.

**Comment by matthew-andrews** [comment]
just to double check…  which version of tar are you using?  `tar --version`

**Comment by JakeChampion** [comment]
bsdtar 2.8.3 - libarchive 2.8.3

**Comment by matthew-andrews** [comment]
ok thanks.
