### ISSUE TITLE
Set buildpack_provided_description on the submitted slug

### ISSUE THREAD

**Issue by edmorley** [matthew-andrews/haikro#110]
Hi!

When haikro is used to build a Heroku app, it generates the slug locally and then records it using the `/apps/{app_id_or_name}/slugs` API:
https://devcenter.heroku.com/articles/platform-api-reference#slug-create

However currently haikro doesn't set the `buildpack_provided_description` attribute on that POST, meaning the apps end up showing with:

> Language: (unknown)

This can cause confusion when interacting with Heroku support, since it's not clear what generated the build.

Please could haikro set `buildpack_provided_description` (perhaps to simply "haikro") to prevent this? :-)

It would need to be passed alongside `process_types` and `commit`, here:
https://github.com/matthew-andrews/haikro/blob/5c73935f658825874edcedcd1b2210a086e056f4/lib/deploy.js#L61-L67

Many thanks!

**Comment by matthew-andrews** [comment]
Hi, wow! thank you for your issue. Let me a make a PR for this.

And apologies for the sequence of events I am imaging happened that led to this issue 😅 !

**Comment by edmorley** [comment]
Thank you for the quick reply and PR!

It's all good - in the ticket in question after being asked to do a `git push heroku master` (as part of debugging a stack upgrade that wasn't taking effect), the person that opened it mentioned that deploys were being performed by haikro - I could just see a scenario where future tickets might not mention this :-)

**Comment by matthew-andrews** [comment]
Released in v2.5.0

**Comment by edmorley** [comment]
Thank you :-)

> I'm also a little bit amazed haikro still works and someone is using it !

The platform APIs and slug format will likely continue to work for some time -- I suspect what may cause issues in the future is the use of semver.io since that service is deprecated. I don't have a good sense of how many apps are using haikro at the moment (the addition of `buildpack_provided_description` will help with that, presuming apps update to 2.5.0) - only the recent ticket.
