### ISSUE TITLE
Sounds evil

### ISSUE THREAD

**Issue by triblondon** [matthew-andrews/haikro#58]
Haikro sounds like a villainous organisation from a Bond film or a Marvel superhero film.  Recommend renaming to "destiny".

**Comment by triblondon** [comment]
This issue is not (entirely) serious.

**Comment by matthew-andrews** [comment]
would you mind making a PR with a failing test?

**Comment by samgiles** [comment]
```JS
it("should not be too evil", function() { 
  assert.isNotTooEvil(require('../package.json').name); 
});
```

**Comment by matthew-andrews** [comment]
nope.
