### ISSUE TITLE
Doesn't support deploy from working dir very well

### ISSUE THREAD

**Issue by triblondon** [matthew-andrews/haikro#59]
If your Makefile runs stuff like `npm prune --production` and `git clean -fxd` then you are going to a) wipe out any untracked files you might be working on, and b) delete all your dev tools.  This seems suboptimal if you intend to continue developing in that clone after the deploy.

As a workaround, I can remember to create a new sacrificial clone and deploy that, but running deploy from a working clone accidentally would be... problematic.

**Comment by matthew-andrews** [comment]
think should probably do the pruning in a dedicated folder
