### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by davglass** [matthew-andrews/haikro#62]
Can you please add a license to your module? Not providing a license is basically "all rights reserved" which means that others can't actually use it. I would recommend MIT, BSD or the like :)

Thanks

**Comment by matthew-andrews** [comment]
oops should be MIT.

**Comment by matthew-andrews** [comment]
is this sufficient for your needs? https://github.com/matthew-andrews/haikro/commit/e57ff2888746c582469dcbc953afbf584dcc9200

**Comment by davglass** [comment]
Much better, thanks :shipit:
