### ISSUE TITLE
Removing dev dependencies can cause problems

### ISSUE THREAD

**Issue by aintgoin2goa** [matthew-andrews/haikro#67]
We have seen 2 seperate issues issue caused by this feature:

In one case the same module was listed in depdencies **and** devDepencies - it was removed by Haikro and the app died.

In the 2nd case there was a dependency listed in devDependencies which was a nested dependency of a third-party module.  Again it was removed and thee app died.

Possible solutions:
*  Try `rm -rf node_modules` then `npm install --production`
*  Analyze dependency structure in some cleve way before removing things

Either way, would recommend making this feature optional

**Comment by samgiles** [comment]
Would enumerating the 'dependencies' and the directory names inside
'node_modules' and excluding the diff from only this directory work?

**Comment by aintgoin2goa** [comment]
Probably, as long as you node_modules was enumerated recursively (or the --exclude pattern is tightened up to not remove anything sub-dependencies)

**Comment by aintgoin2goa** [comment]
Actually thinking about it again, no, that probably wouldn't work.  Here is the exact problem we had:

* **request** added as a devDepedency
* npm installs it directly under node_modules
* Another 3rd-party module lists require as a dependency, but it already exists so npm doesn't download it again
* Haikro removes the dev dependencies including, in this case, something the app needed to work.

The other option is to run `npm install --production` *after* pruning to be sure you have everything you need to deploy.

**Comment by samgiles** [comment]
Yeh i see how this is awkward.  Could reuse this code:
https://github.com/npm/npm/blob/master/lib/prune.js?

**Comment by matthew-andrews** [comment]
will happily accept a PR to rollback to the previous behaviour or something that looks at the deps more deeply

**Comment by matthew-andrews** [comment]
@aintgoin2goa added you as collaborator to haikro

**Comment by matthew-andrews** [comment]
as of npm v2.7.0 you can do `npm ls --production --json` :smile:

**Comment by matthew-andrews** [comment]
this is fixed.
