### ISSUE TITLE
haikro object exposing the api

### ISSUE THREAD

**Issue by AlbertoElias** [matthew-andrews/haikro#68]
Would it be possible to have the API exposed via a general haikro object to be able to use it from a Node app instead of via the command line or requiring each "action" individually?

**Comment by matthew-andrews** [comment]
what's the benefit of doing this over requiring each action individually? eg. `require('haikro/lib/build');`, etc

i'm already commited to maintaining this folder structure because of things like next-build-tools.
https://github.com/Financial-Times/next-build-tools/blob/master/tasks/deploy.js#L7-9

**Comment by AlbertoElias** [comment]
Right now I'm doing:

```js
var haikro = {
	build: require('haikro/lib/build'),
	create: require('haikro/lib/create'),
	deploy: require('haikro/lib/deploy'),
	destroy: require('haikro/lib/destroy')
};
```

Just seems to make more sense to have that done directly in the module and set it as the main file in the package.json, that way we just need to require it once. It's also how most modules that I've used work.

**Comment by matthew-andrews** [comment]
is it not still breaking stuff? we could go back to the old beahviour?

**Comment by matthew-andrews** [comment]
let's talk when i'm back.  know many modules do this, but i've always struggled to see the benefit.

**Comment by AlbertoElias** [comment]
Another benefit would be that you could require the fetch polyfill there, so other apps that use haikro don't need to require it manually.

**Comment by matthew-andrews** [comment]
that's true but I think it's a bug!  https://github.com/matthew-andrews/haikro/issues/70

**Comment by AlbertoElias** [comment]
I guess that's another way of solving that

**Comment by matthew-andrews** [comment]
coming https://github.com/matthew-andrews/haikro/pull/92
