### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by commuterjoy** [matthew-andrews/haikro#75]
{ [Error: stdout maxBuffer exceeded.] cmd: '/bin/sh -c npm ls --production --parseable' }
make: *** [deploy] Error 1

The output of this exec command seems to generate errors. I tried to increase the [stdout buffer](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback), but then I just hit an OS MAX_ARGS limit.

Eg, http://ftjen06392-lvpr-uk-p.osb.ft.com:8181/job/next-service-registry/254/console

npm -v 2.7.4

node -v v0.12.2

**Comment by commuterjoy** [comment]
Ah, yeah, seems to be related to this change ...

https://github.com/matthew-andrews/haikro/commit/2df79f037829954a4a706be1380032bbe0e1a939#diff-26b681bd4dac10f25d5293c7595c435bL109

Some modules are going to produce a lot of directory listings, producing a lot of stdout.

Might need to use a [stream](http://www.hacksparrow.com/difference-between-spawn-and-exec-of-node-js-child_process.html) if you wanted to do this?

**Comment by commuterjoy** [comment]
```
var exec = require('child_process').exec;
var spawn = require('child_process').spawn;

// will chuck a max buffer error
child = exec('find /',
  function (error, stdout, stderr) {
    if (error !== null) {
      console.log('exec error: ' + error);
    }
});

// will list your whole file system
ls = spawn('find', ['/']);
ls.stdout.on('data', function (data) {
  //console.log('stdout: ' + data);
});
```

**Comment by matthew-andrews** [comment]
i think a more elegant fix is reduce the size of the data trying to output:-

https://github.com/matthew-andrews/haikro/pull/76

(does pass and tested with grumman, heroku has just got its knickers in a twist)

**Comment by matthew-andrews** [comment]
ahhh yes you were right……… i do need to do this. it's not erroring on the output it's erroring on the input……

**Comment by matthew-andrews** [comment]
although in this case one of the big dependencies actually should have been a devdep
http://git.svc.ft.com:8080/projects/NEXT/repos/service-registry/commits/fdfa032c1312150e395dcf630c3db2473a3d0a96

**Comment by matthew-andrews** [comment]
and i suspect it'll work now it's not
