### ISSUE TITLE
Refuses to work with npm3

### ISSUE THREAD

**Issue by pornel** [matthew-andrews/haikro#86]
> verbose: Checking NPM version 3.2.0 matches ^2.7.0
> error: Insufficiently new version of npm, please upgrade to v2.7.0 or above.

**Comment by matthew-andrews** [comment]
https://github.com/matthew-andrews/haikro/blob/master/lib/build.js#L31

needs to be `>2.7.0`, right?

**Comment by matthew-andrews** [comment]
do you mind taking this branch for a spin and letting me know if it's good and i'll merge?

https://github.com/matthew-andrews/haikro/pull/87

**Comment by pornel** [comment]
I've changed it to `>=2.7.0` and it worked

**Comment by matthew-andrews** [comment]
ah. `>=`. even better
